name: modrinth
description: An api client for Modrinth resources
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.0
  meta: ^1.7.0
  retrofit: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
  source_gen: ^1.2.1
  # test: ^1.20.2
  retrofit_generator: ^5.0.0
  build_runner: '>2.3.0 <4.0.0' 
  freezed: ^2.2.1
  json_serializable: ^6.5.4
